[package]
name = "opencv-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
opencv = "0.94"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "git-action-test"
path = "src/bin/git-action-test.rs"

[[bin]]
name = "window"
path = "src/bin/window.rs"

[[bin]]
name = "img-write"
path = "src/bin/img-write.rs"

[[bin]]
name = "capvideo"
path = "src/bin/capvideo.rs"

[[bin]]
name = "play-mp4"
path = "src/bin/play-mp4.rs"

[[bin]]
name = "save-camera"
path = "src/bin/save-camera.rs"
