[package]
name = "opencv-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
opencv = "0.94"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "window"
path = "src/bin/window.rs"

[[bin]]
name = "img-write"
path = "src/bin/img-write.rs"

[[bin]]
name = "capvideo"
path = "src/bin/capvideo.rs"
